### ISSUE TITLE
Randüberstand Literaturverzeichnis

### ISSUE THREAD

**Issue by WortPixel** [MaxNoe/TUDoThesis#3]
Die 5. Referenz steht über. Da fehlt evt 
\usepackage{hyphenat}	% adds options to control hyphenation

**Comment by MaxNoe** [comment]
hyphenat wird nichts bringen. Er will das In: scheinbar nicht in die nächste Zeile packen. 

Hab aber mal englische Trennung für die englischen Einträge aktiviert. Siehe  4622222f5ec68d82119b85ac5e1d9192c5bdcc5c

**Comment by MaxNoe** [comment]
Siehe:
http://tex.stackexchange.com/questions/124179/special-line-breaking-problem-in-my-bibliography

Is ein Problem, dass das In: so gerade eben in den Rand kommt und kein dehnbarer Space mehr vorhanden ist. Lässt sich mit der Antwort oben beheben. Da das aber ein seltener Einzelfall sein sollte, packe ich das nicht mit in die Vorlage.
