### ISSUE TITLE
Latexdokument kompiliert nicht

### ISSUE THREAD

**Issue by marian42** [MaxNoe/tudothesis#5]
Mit dem im Dokument angegebenen lualatex-Befehl kann das Dokument nicht gebaut werden. Es treten Fehler und Warnungen auf.

Auch mit  `make` treten Fehler auf.

Weiterhin sollten die Hinweise zum Editor und lualatex-Befehl in der readme stehen, da man die ja lesen sollte, bevor man das Dokument das erste mal baut.

**Comment by MaxNoe** [comment]
Ohne Fehlermeldung kann ich dir nicht helfen.

Mit einem aktuellen TeX Live 2016 kompiliert das Beispiel auf jeden Fall.
Im repo ist auch das fertig gebaute pdf dokument.

**Comment by marian42** [comment]
Ich benutze die aktuelle Version von texlive.
Der Fehler:
`You can't use `\relax' after \the. \begin{document}`
[komplettes log](https://gist.github.com/marian42/10eb2b43161e4ba5e5b9f37c5c7f63b9)

**Comment by MaxNoe** [comment]
Das einzige was ich zu dem Fehler finde ist falls das Paket `apacite` verwendet wird. Das sehe ich aber im log nicht.

Ohne deine Präambel komme ich also nicht weiter. Wenn du die nicht hier hochladen willst, kannst du   auch gerne ne Mail schicken oder bei mir im Büro vorbeikommen.

**Comment by marian42** [comment]
Ist die Präambel nicht Teil des Repositories? Ich hab bei mir keine Dateien verändert.

**Comment by MaxNoe** [comment]
Achso, also du kompilierst das frisch ausgecheckte repo? Das ist seltsam.

Bei mir baut es mit Tex Live 2016 auf Linux (getestet Ubuntu 16.04 und Arch). 

Der Kollege hats auf Mac mit TeX Live 2015 getestet, das läuft auch.

**Comment by MaxNoe** [comment]
Nach ein bisschen mehr googlen, habe ich das hier gefunden:
http://tex.stackexchange.com/questions/291425/lualatex-and-polyglossia-with-setdefaultlanguagegerman-does-not-work-after-re

Dieser Bug sollte mittlerweile gefixt sein, auch in TeX Live 2015.

So kannst du updaten:

1. TeXLive sagen, dass es weiterhin TeXLive 2015 Updates ziehen soll:

```
$ tlmgr option repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
```

2. Updaten:

```
$ tlmgr update --self --all --reinstall-forcibly-removed
```
```

**Comment by marian42** [comment]
Ich habe Ubuntu 16.04 und das Paket texlive-full, das ist anscheinend Version 2015 und nicht 2016. Vielleicht sollte ich das updaten?

Der zweite Befehl scheint nicht zu funktionieren:

```
marian@marian:~/TUDoThesis$ tlmgr update --self --all --reinstall-forcibly-removed
(running on Debian, switching to user mode!)
TeX Live 2015 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read http://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr: package repository ftp://tug.org/historic/systems/texlive/2015/tlnet-final
tlmgr: no updates available

```

**Comment by MaxNoe** [comment]
Ah, du benutzt das Paket aus apt. 

Ich würde fast immer empfehlen, TeX Live nicht aus den Paketquellen zu installieren. Sonder eben direkt von hier: https://www.tug.org/texlive/acquire-netinstall.html.

So wie es auch hier beschrieben ist:
http://toolbox.pep-dortmund.org/install.html

**Comment by marian42** [comment]
Habe texlive jetzt wie beschrieben installiert und damit baut das Dokument.

Im Tutorial ist ein Fehler. Die Zeile
`echo export PATH=\"$(echo ~/.local/texlive/*/bin/*):\$PATH\" >> ~/.bashrc`
muss heißen:
`echo export PATH=\"$(echo /usr/local/texlive/*/bin/*):\$PATH\" >> ~/.bashrc`

Ich persönlich fände es ja schöner, texlive aus der Paketquelle benutzen zu können. Wenn das nicht möglich ist, sollte zumindest in diesem Repository irgendwo stehen, dass man texlive manuell installieren muss. Alle Bachelor-Studenten, die ich kenne, haben versucht, diese Vorlage hier zu benutzen und es nicht hinbekommen.

**Comment by MaxNoe** [comment]
1. Ich kann nichts dafür, dass in den Ubuntu-Paketen noch ein elementarer Bug enthalten ist. Das müssen die Leute fixen, die diese Pakete erstellen. Der Bug tritt immer auf, wenn man biblatex mit der deutschen Sprache verwendet. Also nix, was ich irgendwie auf meiner Seite verhindern kann.

2. Im Tutorial ist kein Fehler. Der angegene Befehl ist korrekt, wenn man den Installationspfad so setzt wie im Tutorial zwei Zeilen drüber angegeben.

3. Man muss TeX Live nicht manuell installieren, wenn die Distribution die man verwendet nicht Mist beim erstellen des Pakets baut. (Oder zu lange braucht um nötige Updates einzupflegen).
