### ISSUE TITLE
reduce white space on pages

### ISSUE THREAD

**Issue by hmoldenhauer** [MaxNoe/tudothesis#8]
there's quite a lot of white space around the text. I think the margins should be reduced

**Comment by MaxNoe** [comment]
No.

See Koma Script Documentation Chapter 1 on how to typeset margins.

If you really want to do this, and I strongly recommend against it, you can set the options yourself.
I won't change them by default.

**Comment by hmoldenhauer** [comment]
I suggest setting DIV=11, so it has the same size as the default font size.
Or set the font size to 12pt. That way DIV will be 12 and the page is filled better.

**Comment by MaxNoe** [comment]
The number in DIV is not related to the font size, it is an integer number of division the page is split into.

KoMa Script determines the DIV number by itself fitting to the font size.

I won't change the default here. If you want to use another setting you are free to do so. Just set the DIV option.
