### ISSUE TITLE
conflict with title length

### ISSUE THREAD

**Issue by hmoldenhauer** [MaxNoe/tudothesis#9]
depending on the length of the title of a thesis the \mbox{(\S\,63 Abs. 5 Hochschulgesetz --HG--).} in eid_versicherung.tex extends into the margins. Is it possible to prevent this somehow?

**Comment by MaxNoe** [comment]
I cannot reproduce this. Thois part of `eid_versicherung.tex` is in  a different paragraph which is not at all affected by the length of the title.

Can you provide a title where this happens and a screenshot of the pdf?

**Comment by MaxNoe** [comment]
I tested this with a title spanning 4 lines.

**Comment by hmoldenhauer** [comment]
I send you an email
